[package]
name = "passhub_for_rspass"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
directories = "5.0"
log = "0.4"
env_logger = "0.10"
url = "2.5.4"
reqwest = { version = "0.11", features = ["blocking"] }